# cli.py

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set

from reqget.config import Config, init_config, load_config, merge_with_args
from reqget.freezecheck import FreezeReport, compare, format_report, get_freeze_dict
from reqget.lockfile import resolve_lockfile, verify_lockfile, write_lockfile
from reqget.resolver import (
    check_conflicts,
    get_dependencies_from_packages,
    get_installed_packages,
    resolve_package,
)
from reqget.scanner import scan_directory_for_imports

try:
    import tkinter as tk
    from tkinter import filedialog, scrolledtext, ttk
except ImportError:
    tk = None  # type: ignore[assignment]


# ── Logging ───────────────────────────────────────────────────────────────────

def _setup_logging(verbose: bool, quiet: bool) -> None:
    level = logging.DEBUG if verbose else (logging.ERROR if quiet else logging.WARNING)
    logging.basicConfig(
        level=level,
        format="%(levelname)s: %(message)s",
        handlers=[logging.StreamHandler(sys.stderr)],
    )


# ── Data helpers ──────────────────────────────────────────────────────────────

def _data_path(filename: str) -> Path:
    return Path(__file__).parent / filename


def load_blacklist(python_version: str, extra: List[str] | None = None) -> Set[str]:
    path = _data_path("blacklist.json")
    try:
        data = json.loads(path.read_text())
        modules = set(data.get(python_version, {}).get("non_pip_modules", []))
    except Exception as exc:
        logging.error("Could not load blacklist: %s", exc)
        modules = set()
    if extra:
        modules.update(extra)
    return modules


def load_conflicts() -> Dict:
    path = _data_path("Knownconflicts.json")
    try:
        return json.loads(path.read_text())
    except Exception as exc:
        logging.error("Could not load conflicts file: %s", exc)
        return {}


def generate_requirements(
    direct_deps: Set[str],
    transitive_map: Dict[str, List[str]],
    output_path: Path,
    *,
    include_transitive: bool = True,
    add_comments: bool = True,
) -> bool:
    from reqget.resolver import _dedup_requirements, _req_name
    try:
        lines: List[str] = []
        if add_comments:
            lines += ["# Generated by reqget", "# Direct dependencies"]
        lines += sorted(direct_deps)

        if include_transitive and transitive_map:
            if add_comments:
                lines += ["", "# Transitive dependencies (sourced from PyPI metadata)"]

            # Collect all raw transitive reqs across every direct dep
            all_raw: Set[str] = {r for reqs in transitive_map.values() for r in reqs}

            # Deduplicate: merge conflicting specifiers for the same package
            deduped = _dedup_requirements(all_raw)

            # Remove anything already listed as a direct dep
            direct_names = {_req_name(d) for d in direct_deps}
            new_trans = sorted(r for r in deduped if _req_name(r) not in direct_names)
            lines += new_trans

        # Always write UTF-8 so Windows doesn't silently use cp1252
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return True
    except OSError as exc:
        logging.error("Could not write %s: %s", output_path, exc)
        return False


# ── Core pipeline ─────────────────────────────────────────────────────────────

def run_scan(
    directory: str,
    cfg: Config,
    *,
    dry_run: bool = False,
) -> bool:
    directory_path = Path(directory).resolve()
    if not directory_path.is_dir():
        logging.error("Not a directory: %s", directory_path)
        return False

    py_ver   = f"{sys.version_info.major}.{sys.version_info.minor}"
    blacklist = load_blacklist(py_ver, cfg.extra_blacklist or [])

    # 1 — scan
    import_map = scan_directory_for_imports(directory_path, blacklist)
    if not import_map:
        print("No third-party imports found.")
        return True

    # 2 — resolve
    installed = get_installed_packages()
    packages: Set[str] = set()
    for module in import_map:
        pkg = resolve_package(module, installed)
        if pkg:
            packages.add(pkg)

    # 3 — deps
    if not cfg.no_transitive:
        print("Fetching transitive dependency info from PyPI…", flush=True)
    direct_deps, transitive_map = get_dependencies_from_packages(
        packages, installed, fetch_transitive=not cfg.no_transitive
    )

    # 4 — conflicts
    triggered = check_conflicts(direct_deps, load_conflicts())
    if triggered:
        print("\n⚠  Potential dependency conflicts detected:")
        for c in triggered:
            print(f"   {' + '.join(c['packages'])}")
            print(f"   Symptoms : {', '.join(c.get('symptoms', []))}")
            print(f"   Fix      : {c.get('resolution', {}).get('suggest', '')}")
        print()

    # 5 — dry run
    if dry_run:
        print("=== Dry run — would write ===")
        for d in sorted(direct_deps):
            print(d)
        return True

    # 6 — requirements.txt
    output_path = directory_path / cfg.output
    ok = generate_requirements(
        direct_deps, transitive_map, output_path,
        include_transitive=not cfg.no_transitive,
        add_comments=not cfg.no_comments,
    )
    if ok:
        print(f"✓ Generated {output_path}  ({len(direct_deps)} direct deps)")

    # 7 — lockfile
    if cfg.lock:
        print("Building lockfile (resolving full dependency tree)…", flush=True)
        pinned, sources = resolve_lockfile(packages, installed)
        lock_path = directory_path / cfg.lock_output
        lok = write_lockfile(pinned, sources, lock_path, direct_names=packages)
        if lok:
            print(f"✓ Generated {lock_path}  ({len(pinned)} packages pinned)")
        ok = ok and lok

    # 8 — freeze check
    if cfg.freeze_check:
        print("\nComparing against pip freeze…")
        freeze = get_freeze_dict()
        report = compare(direct_deps, freeze, ignore_extra=cfg.ignore_extra)
        print(format_report(report))
        if report.has_issues:
            ok = False

    return ok


# ── GUI ───────────────────────────────────────────────────────────────────────

def launch_gui() -> None:
    if not tk:
        print("tkinter is not available. Use the CLI instead.")
        return

    root = tk.Tk()
    root.title("reqget")
    root.resizable(True, True)

    BG      = "#1e1e2e"
    SURFACE = "#2a2a3d"
    ACCENT  = "#7c6af7"
    FG      = "#cdd6f4"
    FG_DIM  = "#6c7086"
    SUCCESS = "#a6e3a1"
    WARNING = "#f9e2af"
    ERROR   = "#f38ba8"

    root.configure(bg=BG)
    root.geometry("680x620")
    root.minsize(560, 500)

    style = ttk.Style(root)
    style.theme_use("clam")
    style.configure("TFrame",        background=BG)
    style.configure("TLabel",        background=BG,      foreground=FG,     font=("Courier New", 11))
    style.configure("Header.TLabel", background=BG,      foreground=ACCENT, font=("Courier New", 18, "bold"))
    style.configure("Dim.TLabel",    background=BG,      foreground=FG_DIM, font=("Courier New", 10))
    style.configure("TEntry",        fieldbackground=SURFACE, foreground=FG, font=("Courier New", 11))
    style.configure("TCheckbutton",  background=BG,      foreground=FG,     font=("Courier New", 10))
    style.map("TCheckbutton",        background=[("active", BG)])
    style.configure("Accent.TButton",
                    background=ACCENT, foreground="#ffffff",
                    font=("Courier New", 11, "bold"), relief="flat", padding=6)
    style.map("Accent.TButton",
              background=[("active", "#6a58e0"), ("disabled", SURFACE)],
              foreground=[("disabled", FG_DIM)])
    style.configure("TButton",
                    background=SURFACE, foreground=FG,
                    font=("Courier New", 11), relief="flat", padding=6)
    style.map("TButton", background=[("active", "#3a3a50")])
    style.configure("TProgressbar", troughcolor=SURFACE, background=ACCENT)

    pad = {"padx": 18, "pady": 5}

    ttk.Label(root, text="reqget",                          style="Header.TLabel").pack(pady=(18, 2))
    ttk.Label(root, text="smart requirements.txt generator",style="Dim.TLabel"  ).pack(pady=(0, 12))

    frm = ttk.Frame(root)
    frm.pack(fill="x", **pad)

    ttk.Label(frm, text="Project path:").grid(row=0, column=0, sticky="w", pady=4)
    dir_var = tk.StringVar()
    ttk.Entry(frm, textvariable=dir_var, width=46).grid(row=0, column=1, sticky="ew", padx=(8, 4))
    ttk.Button(frm, text="Browse…",
               command=lambda: dir_var.set(filedialog.askdirectory() or dir_var.get())
               ).grid(row=0, column=2)

    ttk.Label(frm, text="Output file:").grid(row=1, column=0, sticky="w", pady=4)
    out_var = tk.StringVar(value="requirements.txt")
    ttk.Entry(frm, textvariable=out_var, width=46).grid(row=1, column=1, sticky="ew", padx=(8, 4))

    ttk.Label(frm, text="Lock file:").grid(row=2, column=0, sticky="w", pady=4)
    lock_out_var = tk.StringVar(value="requirements.lock")
    ttk.Entry(frm, textvariable=lock_out_var, width=46).grid(row=2, column=1, sticky="ew", padx=(8, 4))

    frm.columnconfigure(1, weight=1)

    # Options — two columns
    opt_frm = ttk.Frame(root)
    opt_frm.pack(fill="x", **pad)

    no_transitive_var = tk.BooleanVar()
    no_comments_var   = tk.BooleanVar()
    lock_var          = tk.BooleanVar()
    freeze_var        = tk.BooleanVar()
    ignore_extra_var  = tk.BooleanVar()

    opts = [
        ("Skip transitive deps  (faster / offline)", no_transitive_var),
        ("No comments in output",                    no_comments_var),
        ("Generate lockfile",                        lock_var),
        ("Run pip freeze check",                     freeze_var),
        ("Ignore extra packages in freeze check",    ignore_extra_var),
    ]
    for i, (label, var) in enumerate(opts):
        col = i % 2
        row = i // 2
        ttk.Checkbutton(opt_frm, text=label, variable=var).grid(
            row=row, column=col, sticky="w", padx=(0, 20))

    progress = ttk.Progressbar(root, mode="indeterminate")
    progress.pack(fill="x", padx=18, pady=(8, 0))

    log_box = scrolledtext.ScrolledText(
        root, height=12, font=("Courier New", 10),
        bg=SURFACE, fg=FG, insertbackground=FG,
        relief="flat", bd=0, state="disabled",
    )
    log_box.pack(fill="both", expand=True, padx=18, pady=8)
    log_box.tag_config("ok",   foreground=SUCCESS)
    log_box.tag_config("warn", foreground=WARNING)
    log_box.tag_config("err",  foreground=ERROR)

    btn_frm = ttk.Frame(root)
    btn_frm.pack(fill="x", padx=18, pady=(0, 16))

    def _log(msg: str, tag: str = "") -> None:
        log_box.configure(state="normal")
        log_box.insert("end", msg + "\n", tag)
        log_box.see("end")
        log_box.configure(state="disabled")

    def _clear() -> None:
        log_box.configure(state="normal")
        log_box.delete("1.0", "end")
        log_box.configure(state="disabled")

    class _GUILogHandler(logging.Handler):
        _TAG = {logging.WARNING: "warn", logging.ERROR: "err", logging.CRITICAL: "err"}
        def emit(self, record: logging.LogRecord) -> None:
            tag = self._TAG.get(record.levelno, "")
            root.after(0, _log, self.format(record), tag)

    gui_handler = _GUILogHandler()
    gui_handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    logging.getLogger().addHandler(gui_handler)
    logging.getLogger().setLevel(logging.INFO)

    scan_btn = ttk.Button(btn_frm, text="Scan", style="Accent.TButton")
    scan_btn.pack(side="left")
    ttk.Button(btn_frm, text="Clear", command=_clear).pack(side="left", padx=8)
    ttk.Button(btn_frm, text="Quit",  command=root.destroy).pack(side="right")

    def _start_scan() -> None:
        directory = dir_var.get().strip()
        if not directory:
            _log("Please enter or select a project directory.", "err")
            return
        scan_btn.configure(state="disabled")
        progress.start(12)
        _clear()
        _log(f"Scanning {directory}…")
        cfg = Config(
            output         = out_var.get().strip() or "requirements.txt",
            no_transitive  = no_transitive_var.get(),
            no_comments    = no_comments_var.get(),
            lock           = lock_var.get(),
            lock_output    = lock_out_var.get().strip() or "requirements.lock",
            freeze_check   = freeze_var.get(),
            ignore_extra   = ignore_extra_var.get(),
        )
        root.after(50, lambda: _do_scan(directory, cfg))

    def _do_scan(directory: str, cfg: Config) -> None:
        import io, contextlib
        buf = io.StringIO()
        try:
            with contextlib.redirect_stdout(buf):
                ok = run_scan(directory, cfg)
            for line in buf.getvalue().splitlines():
                tag = "ok" if line.startswith("✓") else ("warn" if "⚠" in line else "")
                _log(line, tag)
            _log("Done." if ok else "Finished with issues — check log above.",
                 "ok" if ok else "warn")
        except Exception as exc:
            _log(f"Unexpected error: {exc}", "err")
            logging.exception("GUI scan error")
        finally:
            progress.stop()
            scan_btn.configure(state="normal")

    scan_btn.configure(command=_start_scan)
    root.mainloop()


# ── CLI entry point ───────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="reqget",
        description="Scan a Python project and generate requirements.txt.",
    )
    sub = parser.add_subparsers(dest="command")

    # ── reqget scan (default) ─────────────────────────────────────────────────
    scan_p = sub.add_parser("scan", help="Scan a directory (default command)")
    scan_p.add_argument("directory", nargs="?", help="Project root to scan")
    scan_p.add_argument("-o", "--output",      default=None, metavar="FILE",
                        help="Output filename (default from config or requirements.txt)")
    scan_p.add_argument("--no-transitive",     action="store_true",
                        help="Skip PyPI transitive dep fetch")
    scan_p.add_argument("--no-comments",       action="store_true",
                        help="Omit comment lines from output")
    scan_p.add_argument("--lock",              action="store_true",
                        help="Also write a fully-pinned requirements.lock")
    scan_p.add_argument("--lock-output",       default=None, metavar="FILE",
                        help="Lockfile name (default from config or requirements.lock)")
    scan_p.add_argument("--freeze-check",      action="store_true",
                        help="Diff output against pip freeze")
    scan_p.add_argument("--ignore-extra",      action="store_true",
                        help="Don't flag installed-but-not-found packages in freeze check")
    scan_p.add_argument("--dry-run",           action="store_true",
                        help="Print what would be written; don't write files")
    scan_p.add_argument("--config",            default=None, metavar="FILE",
                        help="Explicit path to a .reqgetrc config file")

    # ── reqget lock ───────────────────────────────────────────────────────────
    lock_p = sub.add_parser("lock", help="Generate a requirements.lock for an existing requirements.txt")
    lock_p.add_argument("directory", help="Project root (must contain requirements.txt)")
    lock_p.add_argument("-i", "--input",  default="requirements.txt", metavar="FILE")
    lock_p.add_argument("-o", "--output", default="requirements.lock", metavar="FILE")

    # ── reqget verify ─────────────────────────────────────────────────────────
    verify_p = sub.add_parser("verify", help="Verify a lockfile's integrity hash")
    verify_p.add_argument("lockfile", help="Path to requirements.lock")

    # ── reqget freeze ─────────────────────────────────────────────────────────
    freeze_p = sub.add_parser("freeze", help="Compare requirements.txt against pip freeze")
    freeze_p.add_argument("requirements", help="Path to requirements.txt")
    freeze_p.add_argument("--ignore-extra", action="store_true",
                           help="Don't flag packages installed but not in requirements")

    # ── reqget init ───────────────────────────────────────────────────────────
    init_p = sub.add_parser("init", help="Create a default .reqgetrc in a directory")
    init_p.add_argument("directory", nargs="?", default=".", help="Where to create .reqgetrc")
    init_p.add_argument("--force", action="store_true", help="Overwrite if it already exists")

    # Global flags (also accepted on the root parser for backward-compat)
    for p in (parser, scan_p):
        p.add_argument("-v", "--verbose", action="store_true")
        p.add_argument("-q", "--quiet",   action="store_true")

    # ── Backward-compat: `reqget <directory>` without subcommand ─────────────
    args = parser.parse_args()

    verbose = getattr(args, "verbose", False)
    quiet   = getattr(args, "quiet",   False)
    _setup_logging(verbose, quiet)

    # No subcommand given
    if not args.command:
        # If a bare directory was given as first positional, treat as 'scan'
        # (argparse won't reach here with a positional since 'scan' is a subcommand,
        #  so this branch handles the GUI / no-args case)
        if tk:
            print("No command provided — launching GUI…")
            launch_gui()
        else:
            parser.print_help()
            sys.exit(1)
        return

    # ── scan ──────────────────────────────────────────────────────────────────
    if args.command == "scan":
        if not args.directory:
            if tk:
                print("No directory provided — launching GUI…")
                launch_gui()
                return
            scan_p.error("directory is required when tkinter is not available")

        cfg = load_config(
            project_dir   = Path(args.directory),
            explicit_path = Path(args.config) if args.config else None,
        )
        cfg = merge_with_args(cfg, args)
        ok  = run_scan(args.directory, cfg, dry_run=getattr(args, "dry_run", False))
        sys.exit(0 if ok else 1)

    # ── lock ──────────────────────────────────────────────────────────────────
    elif args.command == "lock":
        req_path = Path(args.directory) / args.input
        if not req_path.is_file():
            print(f"Error: {req_path} not found.", file=sys.stderr)
            sys.exit(1)
        pkgs: Set[str] = set()
        for line in req_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                name = line.split("==")[0].split(">=")[0].strip()
                pkgs.add(name)
        installed = get_installed_packages()
        print(f"Resolving {len(pkgs)} packages…", flush=True)
        pinned, sources = resolve_lockfile(pkgs, installed)
        out = Path(args.directory) / args.output
        ok  = write_lockfile(pinned, sources, out, direct_names=pkgs)
        if ok:
            print(f"✓ {out}  ({len(pinned)} packages)")
        sys.exit(0 if ok else 1)

    # ── verify ────────────────────────────────────────────────────────────────
    elif args.command == "verify":
        ok, msg = verify_lockfile(args.lockfile)
        print(("✓ " if ok else "✗ ") + msg)
        sys.exit(0 if ok else 1)

    # ── freeze ────────────────────────────────────────────────────────────────
    elif args.command == "freeze":
        req_path = Path(args.requirements)
        if not req_path.is_file():
            print(f"Error: {req_path} not found.", file=sys.stderr)
            sys.exit(1)
        deps: Set[str] = set()
        for line in req_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                deps.add(line)
        freeze = get_freeze_dict()
        report = compare(deps, freeze, ignore_extra=args.ignore_extra)
        print(format_report(report))
        sys.exit(0 if not report.has_issues else 1)

    # ── init ──────────────────────────────────────────────────────────────────
    elif args.command == "init":
        dest_dir = Path(args.directory).resolve()
        try:
            path = init_config(dest_dir, force=args.force)
            print(f"✓ Created {path}")
        except FileExistsError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
