[project]
name = "reqget"
version = "1.0.0"
description = "Smart Python dependency scanner and requirements generator"
authors = [
    { name="Leon Priest", email="your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.md" }
dependencies = [
    "setuptools",  # if needed
    "pkg_resources",
]

[project.scripts]
reqget = "cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
